name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Bandit (SAST)
      run: |
        pip install bandit
        bandit -r . -ll || true

    - name: Run Dependency Scan (pip-audit)
      run: |
        pip install pip-audit
        pip-audit || true

